

# GET http://localhost:3000/v1/users/credentials HTTP/1.1


GET https://proton-angular-builders.herokuapp.com/v1/users/credentials HTTP/1.1
content-type: application/json

{
    "email": "admin@world.org",
    "password": "S3cr3t!"
}